Cub *Cub_rotate_XYZ(Cub *zis);
Cub *Cub_rotate_XZY(Cub *zis);
Cub *Cub_rotate_YXZ(Cub *zis);
Cub *Cub_rotate_YZX(Cub *zis);
Cub *Cub_rotate_ZXY(Cub *zis);
Cub *Cub_rotate_ZYX(Cub *zis);
Cub *Cub_faces_slice_ortho_to_files(Cub *zis, int slice, char *fname);
Cub *Cub_slice_ortho_to_file(Cub *zis, int slice, char *fname);
Cub *Cub_slice_ortho(Cub *zis, Cub *plane, int slice);
Cub *Cub_faces_transparence_ortho_to_files(Cub *zis, Cub *attenuate, char *fname);
Cub *Cub_transparence_ortho_to_file(Cub *zis, Cub *attenuate, char *fname);
Cub *Cub_transparence_ortho(Cub *zis, Cub *plane, Cub *attenuate);
Cub *Cub_faces_transparence_ortho_on_bits_to_files(Cub *zis, Cub *attenuate, char *fname);
Cub *Cub_transparence_ortho_on_bits_to_file(Cub *zis, Cub* attenuate, char *fname);
Cub *Cub_transparence_ortho_on_bits(Cub *zis, Cub *plane, Cub* attenuate);
Cub *Cub_slice_thru_diagonale_to_file(Cub *zis, char *fname);
Cub* Cub_plane_relative_to_files(Cub* zis, char* fname);
Cub* Cub_plane_relative_to_file(Cub* zis, char* fname);
Cub* Cub_plane_relative_move_to_files(Cub* zis, char* fname);
Cub* Cub_plane_relative_move_to_file(Cub* zis, char* fname);
Cub *Cub_volume_to_file(Cub *zis, char *fname);
Cub *Cub_fill(Cub *zis);
