top:
	cat my-others.bib my-references.bib my-spl.bib > my-hack.bib


clean:
	rm -f *~ *.aux *.log *.bbl *.blg *.lof *.lot *.toc nohup.out

noauto:
	rm -rf auto

clobber: clean noauto
	rm -f *.dvi
	rm -f *.ps
	rm -f _region_.*
	rm -f *.fmt
	rm -f mytex
