define(`cat',`$1$2$3$4$5$6$7$8$9')
define(`repeat',`ifelse($1,1,,`$0(decr($1),`$2')')$2')
define(`for',`pushdef(`$1',$2)ifelse($2,$3,,`cat($5,$0(`$1',eval($2+$4),`$3',`$4',`$5'))')popdef(`$1')')
define(`for_bis',`pushdef(`$1',$2)ifelse($2,$3,,`cat($5,$0(`$1',$4,`$3',`$4',`$5'))')popdef(`$1')')
define(`loop',`for(`$1',0,$2,1,`$3')')
define(`def',`define(`$1',bind$2 shift(shift($@))ubind$2)')
define(`bind',`bind1(1,$@)')
define(`bind1',`ifelse($2,,,``pushdef(`$2','cat($,$1)`)'$0(eval($1 + 1),shift(shift($@)))')')
define(`ubind',`ifelse($1,,,``popdef(`$1')'$0(shift($@))')')
define(`bind_def',`bind_def1(1,$@)')
define(`bind_def1',`ifelse($2,,,``pushdef(`$2',`$3')'$0(eval($1 + 1),shift(shiftshift(($@))))')')
define(`ubind_def',`ifelse($1,,,``popdef(`$1')'$0(shift($@))')')
