/* generated defs, dont edit */
#define GAPP_NSI 0
#define GAPP_NSI_POS 0
#define GAPP_NSI_SIZE 3
#define GAPP_NSI_MASK 07
#define GAPP_EWI 1
#define GAPP_EWI_POS 3
#define GAPP_EWI_SIZE 3
#define GAPP_EWI_MASK 070
#define GAPP_CI 2
#define GAPP_CI_POS 6
#define GAPP_CI_SIZE 3
#define GAPP_CI_MASK 0700
#define GAPP_RAMI 3
#define GAPP_RAMI_POS 9
#define GAPP_RAMI_SIZE 2
#define GAPP_RAMI_MASK 03000
#define GAPP_NS 4
#define GAPP_NS_POS 11
#define GAPP_NS_SIZE 1
#define GAPP_NS_MASK 04000
#define GAPP_EW 5
#define GAPP_EW_POS 12
#define GAPP_EW_SIZE 1
#define GAPP_EW_MASK 010000
#define GAPP_C 6
#define GAPP_C_POS 13
#define GAPP_C_SIZE 1
#define GAPP_C_MASK 020000
#define GAPP_SM 7
#define GAPP_SM_POS 14
#define GAPP_SM_SIZE 1
#define GAPP_SM_MASK 040000
#define GAPP_CY 8
#define GAPP_CY_POS 15
#define GAPP_CY_SIZE 1
#define GAPP_CY_MASK 0100000
#define GAPP_BW 9
#define GAPP_BW_POS 16
#define GAPP_BW_SIZE 1
#define GAPP_BW_MASK 0200000
#define GAPP_RAM 10
#define GAPP_RAM_POS 17
#define GAPP_RAM_SIZE 1
#define GAPP_RAM_MASK 0400000
#define GAPP_NOS 11
#define GAPP_NOS_POS 18
#define GAPP_NOS_SIZE 1
#define GAPP_NOS_MASK 01000000
#define GAPP_EOW 12
#define GAPP_EOW_POS 19
#define GAPP_EOW_SIZE 1
#define GAPP_EOW_MASK 02000000
#define GAPP_NNS 0
#define GAPP_NNS_POS 0
#define GAPP_NNS_SIZE 1
#define GAPP_NNS_MASK 01
#define GAPP_NEW 1
#define GAPP_NEW_POS 1
#define GAPP_NEW_SIZE 1
#define GAPP_NEW_MASK 02
#define GAPP_NC 2
#define GAPP_NC_POS 2
#define GAPP_NC_SIZE 1
#define GAPP_NC_MASK 04
#define GAPP_NSM 3
#define GAPP_NSM_POS 3
#define GAPP_NSM_SIZE 1
#define GAPP_NSM_MASK 010
#define GAPP_NCY 4
#define GAPP_NCY_POS 4
#define GAPP_NCY_SIZE 1
#define GAPP_NCY_MASK 020
#define GAPP_NBW 5
#define GAPP_NBW_POS 5
#define GAPP_NBW_SIZE 1
#define GAPP_NBW_MASK 040
#define GAPP_NRAM 6
#define GAPP_NRAM_POS 6
#define GAPP_NRAM_SIZE 1
#define GAPP_NRAM_MASK 0100
#define GAPP_NSINS 0
#define GAPP_NSINS_POS 0
#define GAPP_NSINS_SIZE 3
#define GAPP_NSINS_MASK 07
#define GAPP_EWINS 1
#define GAPP_EWINS_POS 3
#define GAPP_EWINS_SIZE 3
#define GAPP_EWINS_MASK 070
#define GAPP_CINS 2
#define GAPP_CINS_POS 6
#define GAPP_CINS_SIZE 3
#define GAPP_CINS_MASK 0700
#define GAPP_RAMINS 3
#define GAPP_RAMINS_POS 9
#define GAPP_RAMINS_SIZE 2
#define GAPP_RAMINS_MASK 03000
#define GAPP_INS 0
#define GAPP_INS_POS 0
#define GAPP_INS_SIZE 11
#define GAPP_INS_MASK 03777
#define GAPP_REG 1
#define GAPP_REG_POS 11
#define GAPP_REG_SIZE 6
#define GAPP_REG_MASK 0374000
#define GAPP_EXT 2
#define GAPP_EXT_POS 17
#define GAPP_EXT_SIZE 2
#define GAPP_EXT_MASK 01400000
