#define magic(name) MAGIC_ ## name

#define MAGIC_BASE 0

#define MAGIC_STATE_VECT (MAGIC_BASE + 1)
#define MAGIC_CNT_VECT (MAGIC_BASE + 2)
#define MAGIC_STATE_FRAME (MAGIC_BASE + 3)
#define MAGIC_PLANE_FRAME (MAGIC_BASE + 4)
#define MAGIC_CNT_FRAME (MAGIC_BASE + 5)

#define MAGIC_FUNC (MAGIC_BASE + 10)
#define MAGIC_CONEX_TYPE (MAGIC_BASE + 11)
#define MAGIC_CONEX_VAR (MAGIC_BASE + 12)
#define MAGIC_CONEX_VAL (MAGIC_BASE + 13)
#define MAGIC_CONEX_VAR_LIST (MAGIC_BASE + 14)
#define MAGIC_CONEX_VAL_LIST (MAGIC_BASE + 15)
#define MAGIC_CONEX_LIST (MAGIC_BASE + 16)
#define MAGIC_CONEX_SPEC (MAGIC_BASE + 17)

#define MAGIC_XDUMPER_MONO (MAGIC_BASE + 20)

#define MAGIC_SIMPLE (MAGIC_BASE + 30)
#define MAGIC_SIMPLE_2D (MAGIC_BASE + 31)

#define MAGIC_SPACE_1D (MAGIC_BASE + 40)
#define MAGIC_SPACE_2D (MAGIC_BASE + 41)

#define MAGIC_TIME_1D (MAGIC_BASE + 50)
#define MAGIC_TIME_2D (MAGIC_BASE + 51)

#define MAGIC_ACTION (MAGIC_BASE + 60)

#define MAGIC_DUMP_2D (MAGIC_BASE + 70)
#define MAGIC_XDUMP_MONO (MAGIC_BASE + 71)
